export type TableThemeId =
  | 'aurora'
  | 'ocean'
  | 'sunset'
  | 'forest'
  | 'sakura'
  | 'lavender'
  | 'mint'
  | 'amber'
  | 'midnight'
  | 'business'
  | 'rainbow'
  | 'mono'

export interface TableTheme {
  id: TableThemeId
  label: string
  swatches: [string, string, string]
  vars: Record<string, string>
}

function theme(
  id: TableThemeId,
  label: string,
  swatches: [string, string, string],
  vars: Record<string, string>,
): TableTheme {
  return { id, label, swatches, vars }
}

export const TABLE_THEMES: TableTheme[] = [
  theme('aurora', '极光紫', ['#6366f1', '#8b5cf6', '#ec4899'], {
    'table-accent': '#6366f1',
    'table-accent-hover': '#4f46e5',
    'table-accent-light': '#eef2ff',
    'table-accent-soft': 'rgba(99, 102, 241, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #eef2ff 0%, #f5f3ff 100%)',
    'table-title-text': '#4338ca',
    'table-label-bg': '#f8fafc',
    'table-label-text': '#475569',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f8fafc',
    'table-axis-bg': '#f1f5f9',
    'table-axis-corner': '#e2e8f0',
    'table-axis-text': '#64748b',
    'table-axis-active-bg': '#fef3c7',
    'table-axis-active-text': '#92400e',
    'table-border': '#f1f5f9',
    'table-scroll-border': '#e2e8f0',
    'table-formula-bg': '#f8fafc',
    'table-formula-border': '#e2e8f0',
    'table-formula-active-bg': '#eef2ff',
    'table-formula-ref': '#6366f1',
    'table-formula-cell': '#0f766e',
    'table-focus-bg': '#eef2ff',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#fef9c3',
    'table-col-0': '#6366f1',
    'table-col-1': '#8b5cf6',
    'table-col-2': '#ec4899',
    'table-col-3': '#0ea5e9',
    'table-col-4': '#14b8a6',
    'table-col-5': '#f59e0b',
  }),
  theme('ocean', '海洋蓝', ['#0ea5e9', '#06b6d4', '#0284c7'], {
    'table-accent': '#0284c7',
    'table-accent-hover': '#0369a1',
    'table-accent-light': '#e0f2fe',
    'table-accent-soft': 'rgba(14, 165, 233, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #e0f2fe 0%, #ecfeff 100%)',
    'table-title-text': '#0369a1',
    'table-label-bg': '#f0f9ff',
    'table-label-text': '#334155',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f0f9ff',
    'table-axis-bg': '#e0f2fe',
    'table-axis-corner': '#bae6fd',
    'table-axis-text': '#0369a1',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#e0f2fe',
    'table-scroll-border': '#7dd3fc',
    'table-formula-bg': '#f0f9ff',
    'table-formula-border': '#bae6fd',
    'table-formula-active-bg': '#e0f2fe',
    'table-formula-ref': '#0284c7',
    'table-formula-cell': '#0e7490',
    'table-focus-bg': '#e0f2fe',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#cffafe',
    'table-col-0': '#0ea5e9',
    'table-col-1': '#06b6d4',
    'table-col-2': '#0284c7',
    'table-col-3': '#0891b2',
    'table-col-4': '#14b8a6',
    'table-col-5': '#3b82f6',
  }),
  theme('sunset', '落日橙', ['#f97316', '#fb923c', '#ef4444'], {
    'table-accent': '#ea580c',
    'table-accent-hover': '#c2410c',
    'table-accent-light': '#ffedd5',
    'table-accent-soft': 'rgba(249, 115, 22, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #ffedd5 0%, #fef3c7 100%)',
    'table-title-text': '#c2410c',
    'table-label-bg': '#fff7ed',
    'table-label-text': '#57534e',
    'table-row-even': '#ffffff',
    'table-row-odd': '#fff7ed',
    'table-axis-bg': '#ffedd5',
    'table-axis-corner': '#fed7aa',
    'table-axis-text': '#9a3412',
    'table-axis-active-bg': '#fde68a',
    'table-axis-active-text': '#78350f',
    'table-border': '#ffedd5',
    'table-scroll-border': '#fdba74',
    'table-formula-bg': '#fff7ed',
    'table-formula-border': '#fed7aa',
    'table-formula-active-bg': '#ffedd5',
    'table-formula-ref': '#ea580c',
    'table-formula-cell': '#b45309',
    'table-focus-bg': '#ffedd5',
    'table-pick-hover': '#fef08a',
    'table-fill-preview': '#fef3c7',
    'table-col-0': '#f97316',
    'table-col-1': '#fb923c',
    'table-col-2': '#ef4444',
    'table-col-3': '#f59e0b',
    'table-col-4': '#eab308',
    'table-col-5': '#f43f5e',
  }),
  theme('forest', '森林绿', ['#22c55e', '#16a34a', '#059669'], {
    'table-accent': '#16a34a',
    'table-accent-hover': '#15803d',
    'table-accent-light': '#dcfce7',
    'table-accent-soft': 'rgba(34, 197, 94, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #dcfce7 0%, #ecfdf5 100%)',
    'table-title-text': '#166534',
    'table-label-bg': '#f0fdf4',
    'table-label-text': '#44403c',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f0fdf4',
    'table-axis-bg': '#dcfce7',
    'table-axis-corner': '#bbf7d0',
    'table-axis-text': '#166534',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#dcfce7',
    'table-scroll-border': '#86efac',
    'table-formula-bg': '#f0fdf4',
    'table-formula-border': '#bbf7d0',
    'table-formula-active-bg': '#dcfce7',
    'table-formula-ref': '#16a34a',
    'table-formula-cell': '#047857',
    'table-focus-bg': '#dcfce7',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#d1fae5',
    'table-col-0': '#22c55e',
    'table-col-1': '#16a34a',
    'table-col-2': '#059669',
    'table-col-3': '#14b8a6',
    'table-col-4': '#84cc16',
    'table-col-5': '#65a30d',
  }),
  theme('sakura', '樱花粉', ['#f472b6', '#fb7185', '#fda4af'], {
    'table-accent': '#db2777',
    'table-accent-hover': '#be185d',
    'table-accent-light': '#fce7f3',
    'table-accent-soft': 'rgba(244, 114, 182, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #fce7f3 0%, #fff1f2 100%)',
    'table-title-text': '#be185d',
    'table-label-bg': '#fff1f2',
    'table-label-text': '#57534e',
    'table-row-even': '#ffffff',
    'table-row-odd': '#fff1f2',
    'table-axis-bg': '#fce7f3',
    'table-axis-corner': '#fbcfe8',
    'table-axis-text': '#9d174d',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#fce7f3',
    'table-scroll-border': '#f9a8d4',
    'table-formula-bg': '#fff1f2',
    'table-formula-border': '#fbcfe8',
    'table-formula-active-bg': '#fce7f3',
    'table-formula-ref': '#db2777',
    'table-formula-cell': '#be123c',
    'table-focus-bg': '#fce7f3',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#ffe4e6',
    'table-col-0': '#f472b6',
    'table-col-1': '#fb7185',
    'table-col-2': '#fda4af',
    'table-col-3': '#e879f9',
    'table-col-4': '#c084fc',
    'table-col-5': '#f9a8d4',
  }),
  theme('lavender', '薰衣草', ['#a78bfa', '#c4b5fd', '#818cf8'], {
    'table-accent': '#7c3aed',
    'table-accent-hover': '#6d28d9',
    'table-accent-light': '#ede9fe',
    'table-accent-soft': 'rgba(167, 139, 250, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #ede9fe 0%, #f5f3ff 100%)',
    'table-title-text': '#6d28d9',
    'table-label-bg': '#faf5ff',
    'table-label-text': '#475569',
    'table-row-even': '#ffffff',
    'table-row-odd': '#faf5ff',
    'table-axis-bg': '#ede9fe',
    'table-axis-corner': '#ddd6fe',
    'table-axis-text': '#6d28d9',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#ede9fe',
    'table-scroll-border': '#c4b5fd',
    'table-formula-bg': '#faf5ff',
    'table-formula-border': '#ddd6fe',
    'table-formula-active-bg': '#ede9fe',
    'table-formula-ref': '#7c3aed',
    'table-formula-cell': '#6d28d9',
    'table-focus-bg': '#ede9fe',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#f3e8ff',
    'table-col-0': '#a78bfa',
    'table-col-1': '#818cf8',
    'table-col-2': '#c084fc',
    'table-col-3': '#e879f9',
    'table-col-4': '#6366f1',
    'table-col-5': '#8b5cf6',
  }),
  theme('mint', '薄荷青', ['#2dd4bf', '#14b8a6', '#06b6d4'], {
    'table-accent': '#0d9488',
    'table-accent-hover': '#0f766e',
    'table-accent-light': '#ccfbf1',
    'table-accent-soft': 'rgba(45, 212, 191, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #ccfbf1 0%, #ecfeff 100%)',
    'table-title-text': '#0f766e',
    'table-label-bg': '#f0fdfa',
    'table-label-text': '#44403c',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f0fdfa',
    'table-axis-bg': '#ccfbf1',
    'table-axis-corner': '#99f6e4',
    'table-axis-text': '#0f766e',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#ccfbf1',
    'table-scroll-border': '#5eead4',
    'table-formula-bg': '#f0fdfa',
    'table-formula-border': '#99f6e4',
    'table-formula-active-bg': '#ccfbf1',
    'table-formula-ref': '#0d9488',
    'table-formula-cell': '#047857',
    'table-focus-bg': '#ccfbf1',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#cffafe',
    'table-col-0': '#2dd4bf',
    'table-col-1': '#14b8a6',
    'table-col-2': '#06b6d4',
    'table-col-3': '#22d3ee',
    'table-col-4': '#0891b2',
    'table-col-5': '#059669',
  }),
  theme('amber', '琥珀金', ['#f59e0b', '#eab308', '#d97706'], {
    'table-accent': '#d97706',
    'table-accent-hover': '#b45309',
    'table-accent-light': '#fef3c7',
    'table-accent-soft': 'rgba(245, 158, 11, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #fef3c7 0%, #fffbeb 100%)',
    'table-title-text': '#b45309',
    'table-label-bg': '#fffbeb',
    'table-label-text': '#57534e',
    'table-row-even': '#ffffff',
    'table-row-odd': '#fffbeb',
    'table-axis-bg': '#fef3c7',
    'table-axis-corner': '#fde68a',
    'table-axis-text': '#92400e',
    'table-axis-active-bg': '#fed7aa',
    'table-axis-active-text': '#7c2d12',
    'table-border': '#fef3c7',
    'table-scroll-border': '#fcd34d',
    'table-formula-bg': '#fffbeb',
    'table-formula-border': '#fde68a',
    'table-formula-active-bg': '#fef3c7',
    'table-formula-ref': '#d97706',
    'table-formula-cell': '#b45309',
    'table-focus-bg': '#fef3c7',
    'table-pick-hover': '#fef08a',
    'table-fill-preview': '#fde68a',
    'table-col-0': '#f59e0b',
    'table-col-1': '#eab308',
    'table-col-2': '#d97706',
    'table-col-3': '#f97316',
    'table-col-4': '#ca8a04',
    'table-col-5': '#fb923c',
  }),
  theme('midnight', '午夜蓝', ['#1e293b', '#334155', '#6366f1'], {
    'table-accent': '#818cf8',
    'table-accent-hover': '#6366f1',
    'table-accent-light': '#1e293b',
    'table-accent-soft': 'rgba(129, 140, 248, 0.2)',
    'table-title-bg': 'linear-gradient(90deg, #1e293b 0%, #334155 100%)',
    'table-title-text': '#e2e8f0',
    'table-label-bg': '#f1f5f9',
    'table-label-text': '#334155',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f8fafc',
    'table-axis-bg': '#334155',
    'table-axis-corner': '#1e293b',
    'table-axis-text': '#cbd5e1',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#e2e8f0',
    'table-scroll-border': '#475569',
    'table-formula-bg': '#f8fafc',
    'table-formula-border': '#cbd5e1',
    'table-formula-active-bg': '#eef2ff',
    'table-formula-ref': '#6366f1',
    'table-formula-cell': '#4338ca',
    'table-focus-bg': '#eef2ff',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#e0e7ff',
    'table-col-0': '#6366f1',
    'table-col-1': '#818cf8',
    'table-col-2': '#38bdf8',
    'table-col-3': '#2dd4bf',
    'table-col-4': '#a78bfa',
    'table-col-5': '#f472b6',
  }),
  theme('business', '商务灰', ['#1e40af', '#475569', '#64748b'], {
    'table-accent': '#1e40af',
    'table-accent-hover': '#1e3a8a',
    'table-accent-light': '#eff6ff',
    'table-accent-soft': 'rgba(30, 64, 175, 0.1)',
    'table-title-bg': 'linear-gradient(90deg, #eff6ff 0%, #f8fafc 100%)',
    'table-title-text': '#1e3a8a',
    'table-label-bg': '#f8fafc',
    'table-label-text': '#334155',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f8fafc',
    'table-axis-bg': '#e2e8f0',
    'table-axis-corner': '#cbd5e1',
    'table-axis-text': '#475569',
    'table-axis-active-bg': '#fef3c7',
    'table-axis-active-text': '#92400e',
    'table-border': '#e2e8f0',
    'table-scroll-border': '#94a3b8',
    'table-formula-bg': '#f8fafc',
    'table-formula-border': '#cbd5e1',
    'table-formula-active-bg': '#eff6ff',
    'table-formula-ref': '#1e40af',
    'table-formula-cell': '#0f766e',
    'table-focus-bg': '#eff6ff',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#e2e8f0',
    'table-col-0': '#1e40af',
    'table-col-1': '#2563eb',
    'table-col-2': '#475569',
    'table-col-3': '#64748b',
    'table-col-4': '#0f766e',
    'table-col-5': '#334155',
  }),
  theme('rainbow', '彩虹彩', ['#ef4444', '#eab308', '#22c55e'], {
    'table-accent': '#8b5cf6',
    'table-accent-hover': '#7c3aed',
    'table-accent-light': '#f5f3ff',
    'table-accent-soft': 'rgba(139, 92, 246, 0.12)',
    'table-title-bg': 'linear-gradient(90deg, #fef2f2, #fefce8, #ecfdf5, #eff6ff, #f5f3ff)',
    'table-title-text': '#6d28d9',
    'table-label-bg': '#fafafa',
    'table-label-text': '#525252',
    'table-row-even': '#ffffff',
    'table-row-odd': '#fafafa',
    'table-axis-bg': '#f5f5f5',
    'table-axis-corner': '#e5e5e5',
    'table-axis-text': '#737373',
    'table-axis-active-bg': '#fef08a',
    'table-axis-active-text': '#854d0e',
    'table-border': '#f5f5f5',
    'table-scroll-border': '#d4d4d4',
    'table-formula-bg': '#fafafa',
    'table-formula-border': '#e5e5e5',
    'table-formula-active-bg': '#f5f3ff',
    'table-formula-ref': '#8b5cf6',
    'table-formula-cell': '#7c3aed',
    'table-focus-bg': '#f5f3ff',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#fef08a',
    'table-col-0': '#ef4444',
    'table-col-1': '#f97316',
    'table-col-2': '#eab308',
    'table-col-3': '#22c55e',
    'table-col-4': '#3b82f6',
    'table-col-5': '#a855f7',
  }),
  theme('mono', '简约灰', ['#334155', '#64748b', '#94a3b8'], {
    'table-accent': '#475569',
    'table-accent-hover': '#334155',
    'table-accent-light': '#f1f5f9',
    'table-accent-soft': 'rgba(71, 85, 105, 0.1)',
    'table-title-bg': 'linear-gradient(90deg, #f1f5f9 0%, #f8fafc 100%)',
    'table-title-text': '#334155',
    'table-label-bg': '#f8fafc',
    'table-label-text': '#475569',
    'table-row-even': '#ffffff',
    'table-row-odd': '#f8fafc',
    'table-axis-bg': '#e2e8f0',
    'table-axis-corner': '#cbd5e1',
    'table-axis-text': '#64748b',
    'table-axis-active-bg': '#fef3c7',
    'table-axis-active-text': '#92400e',
    'table-border': '#f1f5f9',
    'table-scroll-border': '#cbd5e1',
    'table-formula-bg': '#f8fafc',
    'table-formula-border': '#e2e8f0',
    'table-formula-active-bg': '#f1f5f9',
    'table-formula-ref': '#475569',
    'table-formula-cell': '#334155',
    'table-focus-bg': '#f1f5f9',
    'table-pick-hover': '#fef9c3',
    'table-fill-preview': '#e2e8f0',
    'table-col-0': '#64748b',
    'table-col-1': '#475569',
    'table-col-2': '#94a3b8',
    'table-col-3': '#334155',
    'table-col-4': '#78716c',
    'table-col-5': '#57534e',
  }),
]

export const DEFAULT_TABLE_THEME: TableThemeId = 'aurora'

export function getTableTheme(id: TableThemeId): TableTheme {
  return TABLE_THEMES.find((t) => t.id === id) ?? TABLE_THEMES[0]
}

export function getTableThemeStyle(id: TableThemeId): Record<string, string> {
  const vars = { ...getTableTheme(id).vars }
  const accent = vars['table-accent']
  const scrollBorder = vars['table-scroll-border']
  const border = vars['table-border']

  vars['table-grid-color'] = border
  vars['table-grid-color-strong'] = scrollBorder
  vars['table-border-strong'] = scrollBorder
  vars['table-outer-glow'] = vars['table-accent-soft']
  vars['table-axis-divider'] = scrollBorder
  vars['table-gradient-border'] = `linear-gradient(135deg, ${accent}, ${vars['table-col-2'] ?? accent})`

  return Object.fromEntries(Object.entries(vars).map(([key, value]) => [`--${key}`, value]))
}
